### ISSUE TITLE
[FEAT] : Make navbar Link clickable and attractive

### ISSUE THREAD

**Issue by ayusshh19** [CSI-DMCE-2023/Shopping-Website-PHP-HacktoberFest-2023#3]
Description :- 
Navbar links arent working and not attractive on hover

Screenshot : -
![image](https://github.com/ayusshh19/Hacktoberfest-php/assets/89308426/91f515f0-5fcc-4c17-a99c-33efc96e8f0d)

Expected Outcome : -

- [ ]  Links should look good on hover 
- [ ]  Links should be clickable to render to particular section of page

**Comment by SumitMangrati** [comment]
could you please assign me this task, i am new to open source but i have a fair knowledge on UI design and WEBD, will surely make the navbar look more attractive

**Comment by ayusshh19** [comment]
Sure you can start working !

**Comment by OMPOL1705** [comment]
Looks like this issue is still not resolved. Can you assign it to me.
