### ISSUE TITLE
[FEAT] : make attractive footer

### ISSUE THREAD

**Issue by ayusshh19** [CSI-DMCE-2023/Shopping-Website-PHP-HacktoberFest-2023#4]
Description : - 
Page footer isnt attractive make UI good and responsive

Screeenshot : -
![image](https://github.com/ayusshh19/Hacktoberfest-php/assets/89308426/1b36e4ba-8b29-40d4-84b2-8dbd579277a4)

Expected Outcome : -

- [ ]  Add social media icons
- [ ]  Add company information at left bottom
- [ ]  Add multiple sections

**Comment by Panth1823** [comment]
Hey @ayusshh19 i would like to work on this !

**Comment by ayusshh19** [comment]
Sure you can start contributing !

**Comment by OMPOL1705** [comment]
Looks like a great issue to work on. Please assign it to me.

**Comment by princyballabh** [comment]
Hey, I would like to make the footer attractive and solve the issue.

**Comment by ayusshh19** [comment]
sure you can work ! @OMPOL1705

**Comment by OMPOL1705** [comment]
I have made the required changes and raised PR please see through it.
